print('seja bem vindo a pastelaria devops')
print('faça seu pedido')
item_pedido = input('Qual o sabor do pastel que você deseja?:')
print(f'O pastel pedido foi{item_pedido} - {type(item_pedido)}')
troco = float(input('O valor do pedido é R$ 6.00, digite o  troco: '))
print(f'O tipo de dado armazenado em troco é {type(troco)}')