---
    ansible:
        hosts: 
          ansible-server-prod:
            ansible_host: 162.16.175.32

    server_prod:
        hosts: 
          lab1-centos7-prod:
            ansible_host: 162.16.175.32
          lab2-centos7-prod:
            ansible_host: 162.16.175.32

    client:
      children:
        server_prod:


    backup:
      children:
        client:
