---
    ansible:
        hosts: 
          ansible-server-prod:
            ansible_host: 10.32.7.135

    server_prod:
        hosts: 
          lab1-centos7-prod:
            ansible_host: 10.32.7.134
            ansible_connection: paramiko
          lab2-centos7-prod:
            ansible_host: 10.32.7.66

    client:
      children:
        server_prod:


    backup:
      children:
        client:
